services:
  social-to-mealie:
    restart: unless-stopped
    image: ghcr.io/gerardpollorebozado/social-to-mealie:latest
    container_name: social-to-mealie
    environment:
      - OPENAI_URL=https://api.openai.com/v1 #URL of api endpoint of AI provider
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_MODEL=whisper-1 # this model will be used to transcribe the audio to text
      - MEALIE_URL=https://mealie.example.com # url of you mealie instance
      - MEALIE_API_KEY=${MEALIE_API_KEY}
      # Optional, customize the standard prompt if needed this will replace it
      - USER_PROMPT=Custom prompt
      # Optional, addition to the prompt, useful for translation needs
      - EXTRA_PROMPT=The description, ingredients, and instructions must be provided in Spanish
    ports:
      - 4000:3000
    security_opt:
      - no-new-privileges:true
