services:
  social-to-mealie:
    restart: unless-stopped
    image: ghcr.io/maitrekuc/social-to-mealie-plus:latest
    container_name: social-to-mealie
    ports:
      - 4000:3000
    volumes:
      # Persister la base de données et les données de l'application
      - social-to-mealie-data:/app/data
    security_opt:
      - no-new-privileges:true

volumes:
  social-to-mealie-data:
